device-management-toolkit/ui-toolkit

README.md
Simplify and move bulk of next-step content to Github Pages site for clarity and improved user flow
=> Add readme edits for release of doc site

.github/workflows/node.js.yml, package-lock.json
Signed-off-by: Mike <michael.johanson@intel.com>
=> ci: add simple build for ui-toolkit

package-lock.json, package.json
=> build(dep): bump sass to 1.34.1

README.md
- Switch npm cmd
- Update links to 1.4
- Align formatting to other repos
=> docs(readme): update to v1.4.0 steps

.github/workflows/changelog.yml, .github/workflows/node.js.yml, .github/workflows/publish.yml
=> ci(npm): add job to publish to npm

.github/workflows/deploy.yml
=> ci(deploy): fix broken publish

.github/workflows/node.js.yml
=> ci(workflow): optimize node CI

README.md
=> fix(deps): release all dependency updates since 2.0.3

.github/workflows/release.yml, dist/README.md, dist/package.json
=> fix(build): semantic release should now build code correctly

dist/core/Utilities/MouseHelper.d.ts, src/core/Utilities/MouseHelper.ts, src/test/helper/testdesktop.ts, src/test/helper/testmouseevent.ts, src/test/mousehelper.spec.ts
=> fix: aligns cursor properly when scrolling

.github/workflows/node.js.yml, jest.config.js, package-lock.json, package.json
=> ci(jest): add junit reports

.github/workflows/node.js.yml
=> ci: rename test output

CHANGELOG.md, package-lock.json, package.json
=> fix(deps): release updated dependencies since 2.0.6

package-lock.json, package.json
=> build(deps-dev): update @types/node to 16.11.45

.github/workflows/projectsSync.yaml
=> ci: add project sync to ui-toolkit

.github/workflows/changelog.yml, .github/workflows/codeql-analysis.yml, .github/workflows/deploy.yml, .github/workflows/node.js.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/semantic.yml
=> ci: update actions/checkout, update semantic PR

.github/workflows/changelog.yml
=> ci: fixed changelog

.github/workflows/node.js.yml
=> ci(deps): bump codecov to 3.1.3

.github/workflows/release.yml
=> ci: update node version for semantic release

.github/workflows/release.yml
=> ci: bump semantic_version to 19.0.5

.github/workflows/release.yml
=> ci: pin cycjimmy/semantic-release-action to v3

.github/workflows/deploy.yml, .github/workflows/node.js.yml, .github/workflows/publish.yml, .github/workflows/release.yml
=> ci: update node version and actions/setup-node to v3

CHANGELOG.md, package-lock.json, package.json
=> chore:  update build tasks, package.json and changelog

README.md, dist/README.md
=> docs(readme): update badges

.github/workflows/deploy.yml, .github/workflows/node.js.yml, .github/workflows/publish.yml, .github/workflows/release.yml
=> ci: update to node 20

dist/core/AMTIDER.d.ts, src/core/AMTIDER.ts
=> fix: separated floppy and cdrom read/writes

.gitignore, package-lock.json, src/core/AMTRedirector.ts, src/test/amtider.spec.ts, src/test/amtredirector.spec.ts, src/test/iderDataProcessor.spec.ts
=> feat: add mode query param for kvm, ider and sol

.github/workflows/release.yml
=> fix: update user to use Rosie

.github/workflows/release.yml
=> ci: moves persist-cred false to checkout action

.releaserc.json
=> ci: remove git publish

.releaserc.json
=> ci: update package.json during release

.github/workflows/node.js.yml
=> ci: remove node 16.x from build

src/core/AMTIDER.ts
=> fix: data transfer in ider

package-lock.json
=> chore: updated dependencies

package-lock.json
=> build(deps): update ws dependency

dist/core/AMTIDER.d.ts, dist/core/Utilities/MouseHelper.d.ts, src/core/Utilities/MouseHelper.ts, src/test/mousehelper.spec.ts
=> feat: allow resetting mouse offset

.github/PULL_REQUEST_TEMPLATE.md, README.md, dist/README.md, dist/package.json, package.json
=> refactor: rename open-amt-cloud-toolkit to device-management-toolkit

.github/workflows/release.yml, README.md
=> ci: add @device-management-toolkit publishing for ui-toolkit

.github/workflows/release.yml
=> ci: fix canvas dependency prereqs

.github/workflows/release.yml, README.md, package-lock.json, package.json, src/test/amtdesktop.spec.ts, src/test/imagehelper.spec.ts, src/test/rledecoder.spec.ts
=> fix: remove unnecessary node-canvas dependency

package.json
=> ci: ensure package is set to public

README.md
=> chore: release @device-management-toolkit/ui-toolkit

.github/workflows/projectsSync.yaml, README.md
https://github.com/device-management-toolkit/cloud-deployment/issues/401
=> docs: update status badges in readme to point to new repo
